version: '3.8'

services:
  db:
    container_name: db
    build: 
      context: ./services/mysql
    ports:
      - ${HOST_MYSQL_PORT:-3306}:3306
    environment:
      - MYSQL_DATABASE=app_db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./services/mysql/data:/var/lib/mysql

  backend:
    container_name: backend
    build: 
      context: .
      dockerfile: ./services/php/Dockerfile
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: ./services/npm/Dockerfile
    ports:
      - ${HOST_VITE_PORT:-5173}:5173
    volumes:
      - ./frontend:/app

  web:
    container_name: web
    build: 
      context: ./services/nginx
    ports:
      - ${HOST_NGINX_PORT:-80}:80
    volumes:
      - ./backend:/var/www/html
      - ./services/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
      - frontend
